### ISSUE TITLE
Android - Click on listView item to open details crash the app

### ISSUE THREAD

**Issue by nuno** [FokkeZB/Tracker#12]
If my device have the **"Location"** disabled and I started my "Track" I get no information like **"0 km/h"  or "0 mph"**, beneath the circle with the stop button.

Afterwards I go to the **Rides tab**, I click on ListView Item to get my detail View, is where i get the crash.
If I enable the **"Location"** all works correctly, but then I can't not delete the item that crash the app, because in order to delete an item in this app I have to open the detail View, I'm correct?
Hope this helps!

**Comment by FokkeZB** [comment]
Thanks @nuno, for being the first contributor!

I've fixed the first issue where the dialog that should appear when you don't have the required permission didn't work.

But I cannot reproduce the crash (on iOS), since when location is disabled it doesn't log anything and there's no ride to explore. Can you share the exact steps?

BTW, on iOS you can delete from the list by swiping a ride row to the right.

**Comment by nuno** [comment]
@FokkeZB Glad that I can help :)

Just to confirm @FokkeZB, on iOS there **NO crash**,  and that is why I put in the title of the issue Android - .......

"BTW, on iOS you can delete from the list by swiping a ride row to the right."  **That is correct!**

But since the crash happen on Android I have no way to delete that item, of course I'm testing the app, I can uninstall the app and install again and the items gone.

**Comment by FokkeZB** [comment]
@nuno do you have any crash info?

**Comment by FokkeZB** [comment]
Could you try with the latest code? Just pushed some updates.

**Comment by nuno** [comment]
> @nuno do you have any crash info?

I did the tests on my Android devices, not sure if the device send the logs for you?
Or, I can test via Genymotion ?

> Could you try with the latest code? Just pushed some updates.

Yes, I will do that.

**P.S. The crash's are all in silence.**

**Comment by FokkeZB** [comment]
@nuno did you find time manage to test with the latest code?

I did get a crash via Google Play:

```
java.lang.IllegalArgumentException: southern latitude exceeds northern latitude (NaN > NaN)
    at com.google.android.gms.common.internal.zzu.zzb(Unknown Source)
    at com.google.android.gms.maps.model.LatLngBounds.<init>(Unknown Source)
    at com.google.android.gms.maps.model.LatLngBounds.<init>(Unknown Source)
    at ti.map.TiUIMapView.updateCamera(TiUIMapView.java:373)
    at ti.map.TiUIMapView.processMapProperties(TiUIMapView.java:211)
    at ti.map.TiUIMapView.onMapReady(TiUIMapView.java:162)
    at com.google.android.gms.maps.SupportMapFragment$zza$1.zza(Unknown Source)
    at com.google.android.gms.maps.internal.zzm$zza.onTransact(Unknown Source)
    at android.os.Binder.transact(Binder.java:395)
    at com.google.android.gms.maps.internal.v$a$a.a(:com.google.android.gms.alldynamite:82)
    at maps.ei.bu$6.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6843)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

Which phone is yours?
- Galaxy S6 Edge (zerolte)
- Nexus 5 (hammerhead)
- LENNY2 (s5030)

It looks like the region I set is not correct. I compute the region [here](https://github.com/FokkeZB/Tracker/blob/master/app/controllers/partials/map.js#L31-L70). Would you be able to [get me the SQLite database](http://tonylukasavage.com/blog/2013/04/08/inspecting-sqlite-databases-on-android-and-ios/) which crashes?

**Comment by nuno** [comment]
LENNY2 (s5030)

I will test today, sorry for the delay.
